databricks-cli==0.14.3
datasets==1.6.2
Flask==1.1.2
Flask-Compress==1.9.0
google-auth==1.30.0
google-auth-oauthlib==0.4.4
google-pasta==0.2.0
grpcio==1.34.1
gunicorn==20.1.0
h5py==3.1.0
huggingface-hub==0.0.8
jsonify==0.5
keras-nightly==2.5.0.dev2021032900
Keras-Preprocessing==1.1.2
matplotlib==3.4.2
mlflow==1.17.0
pandas==1.2.4
protobuf==3.16.0
pyarrow==4.0.0
pytorch-lightning==1.3.0
scikit-learn==0.24.2
scipy==1.6.3
seaborn==0.11.1
SQLAlchemy==1.4.14
sqlparse==0.4.1
tokenizers==0.10.2
torch==1.8.1
torchmetrics==0.3.2
torchtext==0.9.1
torchvision==0.9.1
tornado==6.1
tqdm==4.49.0
-e git+https://github.com/huggingface/transformers.git@73fde1defe9be259a47b9024525882f3ec420994#egg=transformers
ts==0.5.1
yarl==1.6.3
