channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- pytorch>=1.6.0
- cudatoolkit>=10.2
- pip
- pip:
  - mlflow
  - scikit-learn
  - pytorch_lightning==1.0.5
  - cloudpickle==1.6.0
  - boto3
  - pandas
  - gorilla
  - ax-platform
  - torchvision

