channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- pytorch>=1.6.0
- torchvision
- pip
- pip:
  - mlflow
  - gorilla
  - sklearn
  - cloudpickle==1.6.0
  - boto3
  - transformers
  - torchtext
  - pytorch-lightning>=1.2.3
